### ISSUE TITLE
Issues when using my own material - InvalidArgumentError (see above for traceback): Incompatible shapes and OOM

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [keithito/tacotron#8]
(Questions in bold font)
I am trying to synthesize my own voice files.

As I did not find a documentation apart from `You can use other datasets if you convert them to the right format. See ljspeech.py for an example.` I used ljspeech and other linking documents, so I ended up with this:

1. I created a folder `myFiles` in the `tacotron` folder with a subfolder `wavs` where I put 147 files WAV-Files that have the pattern `Wav-<6digitnumber>.wav`
1. In the `myFiles` folder, I created `metadata.csv`. I put entries there as in (For illustration purposes, files are in german and the text represents what is being said in the wav-files)
  `Wav-000239|Sentence Number 1.|Sentence Number one.`
  `Wav-000240|Sentence Number 2.|Sentence Number two.`
3. I created a new dataset `myDataset.py`. There I put 
```
    from concurrent.futures import ProcessPoolExecutor
    from functools import partial
    import numpy as np
    import os
    from util import audio
    
    
    def build_from_path(in_dir, out_dir, num_workers=1, tqdm=lambda x: x):
      executor = ProcessPoolExecutor(max_workers=num_workers)
      futures = []
      index = 1
      with open(os.path.join(in_dir, 'metadata.csv'), encoding="utf-8") as f:
        for line in f:
          parts = line.strip().split('|')
          wav_path = os.path.join(in_dir, 'wavs', '%s.wav' % parts[0])
          text = parts[2]
          futures.append(executor.submit(partial(_process_utterance, out_dir, index, wav_path, text)))
          index += 1
      return [future.result() for future in tqdm(futures)]
    
    
    def _process_utterance(out_dir, index, wav_path, text):
      wav = audio.load_wav(wav_path)
      spectrogram = audio.spectrogram(wav).astype(np.float32)
      n_frames = spectrogram.shape[1]
      mel_spectrogram = audio.melspectrogram(wav).astype(np.float32)
      spectrogram_filename = 'myDataset-spec-%05d.npy' % index
      mel_filename = 'myDataset-mel-%05d.npy' % index
      np.save(os.path.join(out_dir, spectrogram_filename), spectrogram.T, allow_pickle=False)
      np.save(os.path.join(out_dir, mel_filename), mel_spectrogram.T, allow_pickle=False)
      return (spectrogram_filename, mel_filename, n_frames, text)
```
 4. I added this to `preprocess.py` and some other files like `train.py` to make it find the files.
```
    def preprocess_mydataset(args):
      in_dir = os.path.join(args.base_dir, 'myFiles')
      out_dir = os.path.join(args.base_dir, args.output)
      os.makedirs(out_dir, exist_ok=True)
      metadata = myDataset.build_from_path(in_dir, out_dir, args.num_workers, tqdm=tqdm)
      write_metadata(metadata, out_dir)  
```
 5. I ran `E:\Python\Anaconda\python.exe preprocess.py --dataset myDataset --output E:\Python\Projekte\tacotron(keithito)\outputmyDataset --base_dir E:\Python\Projekte\tacotron(keithito)` while keeping the settings in `hparams.py`.  I got
```
    100%|████████████████████████████████████████████████████████████████████████████████| 147/147 [00:35<00:00,  4.16it/s]
    Wrote 147 utterances, 112267 frames (0.39 hours)
    Max input length:  284
    Max output length: 1641
```
6. I ran `E:\Python\Anaconda\python.exe train.py --base_dir E:\Python\Projekte\tacotron(keithito) --input E:\Python\Projekte\tacotron(keithito)\outputmyDataset\train.txt` and got
```
    Checkpoint path: E:\Python\Projekte\tacotron(keithito)\logs-tacotron\model.ckpt
    Loading training data from: E:\Python\Projekte\tacotron(keithito)\outputmyDataset\train.txt
    Using model: tacotron
    Hyperparameters:
    adam_beta1: 0.9
    adam_beta2: 0.999
    batch_size: 32
    decay_learning_rate: True
    expand_abbreviations: True
    force_lowercase: True
    frame_length_ms: 50
    frame_shift_ms: 12.5
    griffin_lim_iters: 60
    initial_learning_rate: 0.002
    max_iters: 200
    min_level_db: -100
    num_freq: 1025
    num_mels: 80
    outputs_per_step: 5
    preemphasis: 0.97
    ref_level_db: 20
    sample_rate: 20000
    use_cmudict: False
    Loaded metadata for 147 examples (0.39 hours)
    Initialized Tacotron model. Dimensions:
    embedding:               256
    prenet out:              128
    encoder out:             256
    attention out:           256
    concat attn & out:       512
    decoder cell out:        256
    decoder out (5 frames):  400
    decoder out (1 frame):   80
    postnet out:             256
    linear out:              1025
    2017-07-24 17:34:33.195943: W c:\tf_jenkins\home\workspace\release-win\m\windows-gpu\py\36\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE instructions, but these are available on your machine and could speed up CPU computations.
    2017-07-24 17:34:33.196629: W c:\tf_jenkins\home\workspace\release-win\m\windows-gpu\py\36\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE2 instructions, but these are available on your machine and could speed up CPU computations.
    2017-07-24 17:34:33.197603: W c:\tf_jenkins\home\workspace\release-win\m\windows-gpu\py\36\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
    2017-07-24 17:34:33.198129: W c:\tf_jenkins\home\workspace\release-win\m\windows-gpu\py\36\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
    2017-07-24 17:34:33.198492: W c:\tf_jenkins\home\workspace\release-win\m\windows-gpu\py\36\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
    2017-07-24 17:34:33.198802: W c:\tf_jenkins\home\workspace\release-win\m\windows-gpu\py\36\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
    Starting new training run at commit: None
    Generated 32 batches of size 32 in 3.099 sec
    2017-07-24 17:35:22.258336: W c:\tf_jenkins\home\workspace\release-win\m\windows-gpu\py\36\tensorflow\core\common_runtime\bfc_allocator.cc:217] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.54GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
    2017-07-24 17:35:22.313302: W c:\tf_jenkins\home\workspace\release-win\m\windows-gpu\py\36\tensorflow\core\common_runtime\bfc_allocator.cc:217] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.54GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
    2017-07-24 17:35:22.323448: W c:\tf_jenkins\home\workspace\release-win\m\windows-gpu\py\36\tensorflow\core\common_runtime\bfc_allocator.cc:217] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.54GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
    2017-07-24 17:35:22.334319: W c:\tf_jenkins\home\workspace\release-win\m\windows-gpu\py\36\tensorflow\core\common_runtime\bfc_allocator.cc:217] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.54GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
    2017-07-24 17:35:22.347487: W c:\tf_jenkins\home\workspace\release-win\m\windows-gpu\py\36\tensorflow\core\common_runtime\bfc_allocator.cc:217] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.54GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
    2017-07-24 17:35:22.360685: W c:\tf_jenkins\home\workspace\release-win\m\windows-gpu\py\36\tensorflow\core\common_runtime\bfc_allocator.cc:217] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.54GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
    2017-07-24 17:35:22.374497: W c:\tf_jenkins\home\workspace\release-win\m\windows-gpu\py\36\tensorflow\core\common_runtime\bfc_allocator.cc:217] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.54GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
    2017-07-24 17:35:22.388386: W c:\tf_jenkins\home\workspace\release-win\m\windows-gpu\py\36\tensorflow\core\common_runtime\bfc_allocator.cc:217] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.54GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
    2017-07-24 17:35:22.402800: W c:\tf_jenkins\home\workspace\release-win\m\windows-gpu\py\36\tensorflow\core\common_runtime\bfc_allocator.cc:217] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.54GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
    2017-07-24 17:35:22.417711: W c:\tf_jenkins\home\workspace\release-win\m\windows-gpu\py\36\tensorflow\core\common_runtime\bfc_allocator.cc:217] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.54GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
    2017-07-24 17:35:34.041530: W c:\tf_jenkins\home\workspace\release-win\m\windows-gpu\py\36\tensorflow\core\common_runtime\bfc_allocator.cc:273] Allocator (GPU_0_bfc) ran out of memory trying to allocate 68.82MiB.  Current allocation summary follows.
    2017-07-24 17:35:34.073278: W c:\tf_jenkins\home\workspace\release-win\m\windows-gpu\py\36\tensorflow\core\common_runtime\bfc_allocator.cc:277] *************************************************************************************************___
    2017-07-24 17:35:34.073377: W c:\tf_jenkins\home\workspace\release-win\m\windows-gpu\py\36\tensorflow\core\framework\op_kernel.cc:1158] Resource exhausted: OOM when allocating tensor with shape[17600,1025]
    Exiting due to exception: OOM when allocating tensor with shape[17600,1025]
         [[Node: model/inference/dense/Tensordot/MatMul = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false, _device="/job:localhost/replica:0/task:0/gpu:0"](model/inference/dense/Tensordot/Reshape, model/inference/dense/Tensordot/Reshape_1)]]
         [[Node: model/loss/add_1/_1499 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_24486_model/loss/add_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
    
    Caused by op 'model/inference/dense/Tensordot/MatMul', defined at:
    File "train.py", line 152, in <module>
    main()
    File "train.py", line 148, in main
    train(log_dir, args)
    File "train.py", line 63, in train
    model.initialize(feeder.inputs, feeder.input_lengths, feeder.mel_targets, feeder.linear_targets)
    File "E:\Python\Projekte\tacotron(keithito)\models\tacotron.py", line 84, in initialize
    linear_outputs = tf.layers.dense(post_outputs, hp.num_freq)               # [N, T_out, F]
    File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\layers\core.py", line 215, in dense
    return layer.apply(inputs)
    File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\layers\base.py", line 492, in apply
    return self.__call__(inputs, *args, **kwargs)
    File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\layers\base.py", line 441, in __call__
    outputs = self.call(inputs, *args, **kwargs)
    File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\layers\core.py", line 137, in call
    [0]])
    File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\ops\math_ops.py", line 2421, in tensordot
    ab_matmul = matmul(a_reshape, b_reshape)
    File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\ops\math_ops.py", line 1816, in matmul
    a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)
    File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 1217, in _mat_mul
    transpose_b=transpose_b, name=name)
    File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 767, in apply_op
    op_def=op_def)
    File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\framework\ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
    File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\framework\ops.py", line 1269, in __init__
    self._traceback = _extract_stack()
    
    ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[17600,1025]
         [[Node: model/inference/dense/Tensordot/MatMul = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false, _device="/job:localhost/replica:0/task:0/gpu:0"](model/inference/dense/Tensordot/Reshape, model/inference/dense/Tensordot/Reshape_1)]]
         [[Node: model/loss/add_1/_1499 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_24486_model/loss/add_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
    
    Traceback (most recent call last):
    File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\client\session.py", line 1139, in _do_call
    return fn(*args)
    File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\client\session.py", line 1121, in _run_fn
    status, run_metadata)
    File "E:\Python\Anaconda\lib\contextlib.py", line 89, in __exit__
    next(self.gen)
    File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
    tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[17600,1025]
         [[Node: model/inference/dense/Tensordot/MatMul = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false, _device="/job:localhost/replica:0/task:0/gpu:0"](model/inference/dense/Tensordot/Reshape, model/inference/dense/Tensordot/Reshape_1)]]
         [[Node: model/loss/add_1/_1499 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_24486_model/loss/add_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
    File "train.py", line 92, in train
    step, loss, opt = sess.run([global_step, model.loss, model.optimize])
    File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\client\session.py", line 789, in run
    run_metadata_ptr)
    File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\client\session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
    File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\client\session.py", line 1132, in _do_run
    target_list, options, run_metadata)
    File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\client\session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
    tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[17600,1025]
         [[Node: model/inference/dense/Tensordot/MatMul = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false, _device="/job:localhost/replica:0/task:0/gpu:0"](model/inference/dense/Tensordot/Reshape, model/inference/dense/Tensordot/Reshape_1)]]
         [[Node: model/loss/add_1/_1499 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_24486_model/loss/add_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
    
    Caused by op 'model/inference/dense/Tensordot/MatMul', defined at:
    File "train.py", line 152, in <module>
    main()
    File "train.py", line 148, in main
    train(log_dir, args)
    File "train.py", line 63, in train
    model.initialize(feeder.inputs, feeder.input_lengths, feeder.mel_targets, feeder.linear_targets)
    File "E:\Python\Projekte\tacotron(keithito)\models\tacotron.py", line 84, in initialize
    linear_outputs = tf.layers.dense(post_outputs, hp.num_freq)               # [N, T_out, F]
    File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\layers\core.py", line 215, in dense
    return layer.apply(inputs)
    File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\layers\base.py", line 492, in apply
    return self.__call__(inputs, *args, **kwargs)
    File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\layers\base.py", line 441, in __call__
    outputs = self.call(inputs, *args, **kwargs)
    File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\layers\core.py", line 137, in call
    [0]])
    File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\ops\math_ops.py", line 2421, in tensordot
    ab_matmul = matmul(a_reshape, b_reshape)
    File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\ops\math_ops.py", line 1816, in matmul
    a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)
    File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 1217, in _mat_mul
    transpose_b=transpose_b, name=name)
    File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 767, in apply_op
    op_def=op_def)
    File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\framework\ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
    File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\framework\ops.py", line 1269, in __init__
    self._traceback = _extract_stack()
    
    ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[17600,1025]
         [[Node: model/inference/dense/Tensordot/MatMul = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false, _device="/job:localhost/replica:0/task:0/gpu:0"](model/inference/dense/Tensordot/Reshape, model/inference/dense/Tensordot/Reshape_1)]]
         [[Node: model/loss/add_1/_1499 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_24486_model/loss/add_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
    
    2017-07-24 17:35:34.645288: W c:\tf_jenkins\home\workspace\release-win\m\windows-gpu\py\36\tensorflow\core\kernels\queue_base.cc:294] _0_datafeeder/input_queue: Skipping cancelled enqueue attempt with queue not closed
    Traceback (most recent call last):
    File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\client\session.py", line 1139, in _do_call
    return fn(*args)
    File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\client\session.py", line 1121, in _run_fn
    status, run_metadata)
    File "E:\Python\Anaconda\lib\contextlib.py", line 89, in __exit__
    next(self.gen)
    File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
    tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled
         [[Node: datafeeder/input_queue_enqueue = QueueEnqueueV2[Tcomponents=[DT_INT32, DT_INT32, DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](datafeeder/input_queue, _arg_datafeeder/inputs_0_1, _arg_datafeeder/input_lengths_0_0, _arg_datafeeder/mel_targets_0_3, _arg_datafeeder/linear_targets_0_2)]]
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
    File "E:\Python\Projekte\tacotron(keithito)\datasets\datafeeder.py", line 73, in run
    self._enqueue_next_group()
    File "E:\Python\Projekte\tacotron(keithito)\datasets\datafeeder.py", line 95, in _enqueue_next_group
    self._session.run(self._enqueue_op, feed_dict=feed_dict)
    File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\client\session.py", line 789, in run
    run_metadata_ptr)
    File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\client\session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
    File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\client\session.py", line 1132, in _do_run
    target_list, options, run_metadata)
    File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\client\session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
    tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled
         [[Node: datafeeder/input_queue_enqueue = QueueEnqueueV2[Tcomponents=[DT_INT32, DT_INT32, DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](datafeeder/input_queue, _arg_datafeeder/inputs_0_1, _arg_datafeeder/input_lengths_0_0, _arg_datafeeder/mel_targets_0_3, _arg_datafeeder/linear_targets_0_2)]]
    
    Caused by op 'datafeeder/input_queue_enqueue', defined at:
    File "train.py", line 152, in <module>
    main()
    File "train.py", line 148, in main
    train(log_dir, args)
    File "train.py", line 57, in train
    feeder = DataFeeder(coord, input_path, hparams)
    File "E:\Python\Projekte\tacotron(keithito)\datasets\datafeeder.py", line 44, in __init__
    self._enqueue_op = queue.enqueue(self._placeholders)
    File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\ops\data_flow_ops.py", line 321, in enqueue
    self._queue_ref, vals, name=scope)
    File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\ops\gen_data_flow_ops.py", line 1191, in _queue_enqueue_v2
    name=name)
    File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 767, in apply_op
    op_def=op_def)
    File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\framework\ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
    File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\framework\ops.py", line 1269, in __init__
    self._traceback = _extract_stack()
    
    CancelledError (see above for traceback): Enqueue operation was cancelled
         [[Node: datafeeder/input_queue_enqueue = QueueEnqueueV2[Tcomponents=[DT_INT32, DT_INT32, DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](datafeeder/input_queue, _arg_datafeeder/inputs_0_1, _arg_datafeeder/input_lengths_0_0, _arg_datafeeder/mel_targets_0_3, _arg_datafeeder/linear_targets_0_2)]]
```         
  which sounds like a memory problem of the gpu here - **is there another option to still run it on the GPU(I have 2GB RAM in the GPU)?**
 7. So I set `CUDA_VISIBLE_DEVICES` to `-1` and reran.
```
    ....
    2017-07-24 17:44:19.540072: E c:\tf_jenkins\home\workspace\release-win\m\windows-gpu\py\36\tensorflow\stream_executor\cuda\cuda_driver.cc:406] failed call to cuInit: CUDA_ERROR_NO_DEVICE
    Starting new training run at commit: None
    Generated 32 batches of size 32 in 21.149 sec
    Step 1       [33.743 sec/step, loss=0.88259, avg_loss=0.88259]
    Step 2       [21.797 sec/step, loss=0.88420, avg_loss=0.88340]
    Exiting due to exception: Incompatible shapes: [32,1325,80] vs. [32,1000,80]
             [[Node: model/optimizer/gradients/model/loss/sub_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _device="/job:localhost/replica:0/task:0/cpu:0"](model/optimizer/gradients/model/loss/sub_grad/Shape, model/optimizer/gradients/model/loss/sub_grad/Shape_1)]]
    
    Caused by op 'model/optimizer/gradients/model/loss/sub_grad/BroadcastGradientArgs', defined at:
      File "train.py", line 152, in <module>
        main()
      File "train.py", line 148, in main
        train(log_dir, args)
      File "train.py", line 65, in train
        model.add_optimizer(global_step)
      File "E:\Python\Projekte\tacotron(keithito)\models\tacotron.py", line 134, in add_optimizer
        gradients, variables = zip(*optimizer.compute_gradients(self.loss))
      File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\training\optimizer.py", line 386, in compute_gradients
        colocate_gradients_with_ops=colocate_gradients_with_ops)
      File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\ops\gradients_impl.py", line 540, in gradients
        grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
      File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\ops\gradients_impl.py", line 346, in _MaybeCompile
        return grad_fn()  # Exit early
      File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\ops\gradients_impl.py", line 540, in <lambda>
        grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
      File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\ops\math_grad.py", line 650, in _SubGrad
        rx, ry = gen_array_ops._broadcast_gradient_args(sx, sy)
      File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 395, in _broadcast_gradient_args
        name=name)
      File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 767, in apply_op
        op_def=op_def)
      File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\framework\ops.py", line 2506, in create_op
        original_op=self._default_original_op, op_def=op_def)
      File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\framework\ops.py", line 1269, in __init__
        self._traceback = _extract_stack()
    
    ...which was originally created as op 'model/loss/sub', defined at:
      File "train.py", line 152, in <module>
        main()
    [elided 0 identical lines from previous traceback]
      File "train.py", line 148, in main
        train(log_dir, args)
      File "train.py", line 64, in train
        model.add_loss()
      File "E:\Python\Projekte\tacotron(keithito)\models\tacotron.py", line 113, in add_loss
        self.mel_loss = tf.reduce_mean(tf.abs(self.mel_targets - self.mel_outputs))
      File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\ops\math_ops.py", line 838, in binary_op_wrapper
        return func(x, y, name=name)
      File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 2501, in _sub
        result = _op_def_lib.apply_op("Sub", x=x, y=y, name=name)
      File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 767, in apply_op
        op_def=op_def)
      File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\framework\ops.py", line 2506, in create_op
        original_op=self._default_original_op, op_def=op_def)
      File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\framework\ops.py", line 1269, in __init__
        self._traceback = _extract_stack()
    
    InvalidArgumentError (see above for traceback): Incompatible shapes: [32,1325,80] vs. [32,1000,80]
             [[Node: model/optimizer/gradients/model/loss/sub_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _device="/job:localhost/replica:0/task:0/cpu:0"](model/optimizer/gradients/model/loss/sub_grad/Shape, model/optimizer/gradients/model/loss/sub_grad/Shape_1)]]
    
    Traceback (most recent call last):
      File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\client\session.py", line 1139, in _do_call
        return fn(*args)
      File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\client\session.py", line 1121, in _run_fn
        status, run_metadata)
      File "E:\Python\Anaconda\lib\contextlib.py", line 89, in __exit__
        next(self.gen)
      File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 466, in raise_exception_on_not_ok_status
        pywrap_tensorflow.TF_GetCode(status))
    tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [32,1325,80] vs. [32,1000,80]
             [[Node: model/optimizer/gradients/model/loss/sub_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _device="/job:localhost/replica:0/task:0/cpu:0"](model/optimizer/gradients/model/loss/sub_grad/Shape, model/optimizer/gradients/model/loss/sub_grad/Shape_1)]]
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "train.py", line 92, in train
        step, loss, opt = sess.run([global_step, model.loss, model.optimize])
      File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\client\session.py", line 789, in run
        run_metadata_ptr)
      File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\client\session.py", line 997, in _run
        feed_dict_string, options, run_metadata)
      File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\client\session.py", line 1132, in _do_run
        target_list, options, run_metadata)
      File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\client\session.py", line 1152, in _do_call
        raise type(e)(node_def, op, message)
    tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [32,1325,80] vs. [32,1000,80]
             [[Node: model/optimizer/gradients/model/loss/sub_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _device="/job:localhost/replica:0/task:0/cpu:0"](model/optimizer/gradients/model/loss/sub_grad/Shape, model/optimizer/gradients/model/loss/sub_grad/Shape_1)]]
    
    Caused by op 'model/optimizer/gradients/model/loss/sub_grad/BroadcastGradientArgs', defined at:
      File "train.py", line 152, in <module>
        main()
      File "train.py", line 148, in main
        train(log_dir, args)
      File "train.py", line 65, in train
        model.add_optimizer(global_step)
      File "E:\Python\Projekte\tacotron(keithito)\models\tacotron.py", line 134, in add_optimizer
        gradients, variables = zip(*optimizer.compute_gradients(self.loss))
      File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\training\optimizer.py", line 386, in compute_gradients
        colocate_gradients_with_ops=colocate_gradients_with_ops)
      File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\ops\gradients_impl.py", line 540, in gradients
        grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
      File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\ops\gradients_impl.py", line 346, in _MaybeCompile
        return grad_fn()  # Exit early
      File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\ops\gradients_impl.py", line 540, in <lambda>
        grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
      File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\ops\math_grad.py", line 650, in _SubGrad
        rx, ry = gen_array_ops._broadcast_gradient_args(sx, sy)
      File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 395, in _broadcast_gradient_args
        name=name)
      File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 767, in apply_op
        op_def=op_def)
      File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\framework\ops.py", line 2506, in create_op
        original_op=self._default_original_op, op_def=op_def)
      File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\framework\ops.py", line 1269, in __init__
        self._traceback = _extract_stack()
    
    ...which was originally created as op 'model/loss/sub', defined at:
      File "train.py", line 152, in <module>
        main()
    [elided 0 identical lines from previous traceback]
      File "train.py", line 148, in main
        train(log_dir, args)
      File "train.py", line 64, in train
        model.add_loss()
      File "E:\Python\Projekte\tacotron(keithito)\models\tacotron.py", line 113, in add_loss
        self.mel_loss = tf.reduce_mean(tf.abs(self.mel_targets - self.mel_outputs))
      File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\ops\math_ops.py", line 838, in binary_op_wrapper
        return func(x, y, name=name)
      File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 2501, in _sub
        result = _op_def_lib.apply_op("Sub", x=x, y=y, name=name)
      File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 767, in apply_op
        op_def=op_def)
      File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\framework\ops.py", line 2506, in create_op
        original_op=self._default_original_op, op_def=op_def)
      File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\framework\ops.py", line 1269, in __init__
        self._traceback = _extract_stack()
    
    InvalidArgumentError (see above for traceback): Incompatible shapes: [32,1325,80] vs. [32,1000,80]
             [[Node: model/optimizer/gradients/model/loss/sub_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _device="/job:localhost/replica:0/task:0/cpu:0"](model/optimizer/gradients/model/loss/sub_grad/Shape, model/optimizer/gradients/model/loss/sub_grad/Shape_1)]]
    
    2017-07-24 17:46:28.842837: W c:\tf_jenkins\home\workspace\release-win\m\windows-gpu\py\36\tensorflow\core\kernels\queue_base.cc:294] _0_datafeeder/input_queue: Skipping cancelled enqueue attempt with queue not closed
    Traceback (most recent call last):
      File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\client\session.py", line 1139, in _do_call
        return fn(*args)
      File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\client\session.py", line 1121, in _run_fn
        status, run_metadata)
      File "E:\Python\Anaconda\lib\contextlib.py", line 89, in __exit__
        next(self.gen)
      File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 466, in raise_exception_on_not_ok_status
        pywrap_tensorflow.TF_GetCode(status))
    tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled
             [[Node: datafeeder/input_queue_enqueue = QueueEnqueueV2[Tcomponents=[DT_INT32, DT_INT32, DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](datafeeder/input_queue, _arg_datafeeder/inputs_0_1, _arg_datafeeder/input_lengths_0_0, _arg_datafeeder/mel_targets_0_3, _arg_datafeeder/linear_targets_0_2)]]
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "E:\Python\Projekte\tacotron(keithito)\datasets\datafeeder.py", line 73, in run
        self._enqueue_next_group()
      File "E:\Python\Projekte\tacotron(keithito)\datasets\datafeeder.py", line 95, in _enqueue_next_group
        self._session.run(self._enqueue_op, feed_dict=feed_dict)
      File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\client\session.py", line 789, in run
        run_metadata_ptr)
      File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\client\session.py", line 997, in _run
        feed_dict_string, options, run_metadata)
      File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\client\session.py", line 1132, in _do_run
        target_list, options, run_metadata)
      File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\client\session.py", line 1152, in _do_call
        raise type(e)(node_def, op, message)
    tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled
             [[Node: datafeeder/input_queue_enqueue = QueueEnqueueV2[Tcomponents=[DT_INT32, DT_INT32, DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](datafeeder/input_queue, _arg_datafeeder/inputs_0_1, _arg_datafeeder/input_lengths_0_0, _arg_datafeeder/mel_targets_0_3, _arg_datafeeder/linear_targets_0_2)]]
    
    Caused by op 'datafeeder/input_queue_enqueue', defined at:
      File "train.py", line 152, in <module>
        main()
      File "train.py", line 148, in main
        train(log_dir, args)
      File "train.py", line 57, in train
        feeder = DataFeeder(coord, input_path, hparams)
      File "E:\Python\Projekte\tacotron(keithito)\datasets\datafeeder.py", line 44, in __init__
        self._enqueue_op = queue.enqueue(self._placeholders)
      File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\ops\data_flow_ops.py", line 321, in enqueue
        self._queue_ref, vals, name=scope)
      File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\ops\gen_data_flow_ops.py", line 1191, in _queue_enqueue_v2
        name=name)
      File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 767, in apply_op
        op_def=op_def)
      File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\framework\ops.py", line 2506, in create_op
        original_op=self._default_original_op, op_def=op_def)
      File "E:\Python\Anaconda\lib\site-packages\tensorflow\python\framework\ops.py", line 1269, in __init__
        self._traceback = _extract_stack()
    
    CancelledError (see above for traceback): Enqueue operation was cancelled
             [[Node: datafeeder/input_queue_enqueue = QueueEnqueueV2[Tcomponents=[DT_INT32, DT_INT32, DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](datafeeder/input_queue, _arg_datafeeder/inputs_0_1, _arg_datafeeder/input_lengths_0_0, _arg_datafeeder/mel_targets_0_3, _arg_datafeeder/linear_targets_0_2)]]
```         
         
**What does that mean and how to fix it?**

**Comment by keithito** [comment]
I'll follow up with a more complete answer in a bit but hopefully this will help you out:

Q: Is there another option to still run in on the GPU(I have 2GB RAM in the GPU)?
A: 2GB is cutting it kind of close, but you might try decreasing the batch size or limiting the length of your output sequences (i.e. the wavs). I'm not sure if that will work though, it still might be too much to fit in 2GB.

Q: What does that mean and how to fix it?
A: There's a limit to the number of iterations that the decoder will run, controlled by the `max_iters` hyperparameter. Try setting it to be at least your maximum output sequence length divided by outputs_per_step. In your case, it looks like you could set it to 330.

**Comment by sonach** [comment]
With default settings, the training need GPU memory about 15627MiB. So 2GB should be too small. As keithito suggested, you can try to decrease your batch size(the default setting is 32. you can decrease to 4, for example).

**Comment by ErfolgreichCharismatisch** [comment]
That solved the issues. Great.
